# Generated by Django 5.2.14 on 2026-06-09 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInverMonitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_max', models.FloatField(default=35.0, verbose_name='Temperatura Máxima (°C)')),
                ('temp_min', models.FloatField(default=15.0, verbose_name='Temperatura Mínima (°C)')),
                ('hum_max', models.FloatField(default=80.0, verbose_name='Humedad Máxima (%)')),
                ('hum_min', models.FloatField(default=40.0, verbose_name='Humedad Mínima (%)')),
                ('lux_max', models.IntegerField(default=60000, verbose_name='Luminosidad Máxima (Lx)')),
                ('lux_min', models.IntegerField(default=10, verbose_name='Luminosidad Mínima (Lx)')),
                ('correo_alerta', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico para notificaciones')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_alarma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Alarma',
                'verbose_name_plural': 'Configuraciones de Alertas',
            },
        ),
        migrations.CreateModel(
            name='RegistroSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('luminosidad', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Sensor',
                'verbose_name_plural': 'Registros de Sensor',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
