# Generated by Django 5.2.14 on 2026-06-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInverMonitor', '0002_configuracionalarma_registrosensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionalarma',
            name='suelo_max',
            field=models.FloatField(default=70.0, verbose_name='Máxima humedad del suelo (%)'),
        ),
        migrations.AddField(
            model_name='configuracionalarma',
            name='suelo_min',
            field=models.FloatField(default=20.0, verbose_name='Mínima humedad del suelo (%)'),
        ),
        migrations.AddField(
            model_name='registrosensor',
            name='humedad_suelo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
