# Generated by Django 5.2.14 on 2026-06-11 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInverMonitor', '0003_configuracionalarma_suelo_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('luminosidad', 'Luminosidad'), ('humedad_suelo', 'Humedad del Suelo')], max_length=20)),
                ('tipo', models.CharField(choices=[('alta', 'Crítica Alta'), ('baja', 'Crítica Baja')], max_length=4)),
                ('valor', models.FloatField()),
                ('umbral_min', models.FloatField()),
                ('umbral_max', models.FloatField()),
                ('correo_enviado_a', models.EmailField(max_length=254)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('leida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Alerta',
                'verbose_name_plural': 'Notificaciones de Alertas',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
