# Generated by Django 5.2.14 on 2026-06-21 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInverMonitor', '0004_notificacionalerta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionalarma',
            name='correo_alerta',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracionalarma',
            name='hum_max',
            field=models.FloatField(default=80.0),
        ),
        migrations.AlterField(
            model_name='configuracionalarma',
            name='hum_min',
            field=models.FloatField(default=40.0),
        ),
        migrations.AlterField(
            model_name='configuracionalarma',
            name='lux_max',
            field=models.IntegerField(default=60000),
        ),
        migrations.AlterField(
            model_name='configuracionalarma',
            name='lux_min',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='configuracionalarma',
            name='suelo_max',
            field=models.FloatField(default=70.0),
        ),
        migrations.AlterField(
            model_name='configuracionalarma',
            name='suelo_min',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='configuracionalarma',
            name='temp_max',
            field=models.FloatField(default=35.0),
        ),
        migrations.AlterField(
            model_name='configuracionalarma',
            name='temp_min',
            field=models.FloatField(default=15.0),
        ),
        migrations.CreateModel(
            name='UltimaAlertaEnviar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=50)),
                ('fecha_envio', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimas_alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'sensor')},
            },
        ),
    ]
