# Generated by Django 5.2.14 on 2026-06-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInverMonitor', '0005_alter_configuracionalarma_correo_alerta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UltimaAlertaEnviar',
        ),
    ]
